### ISSUE TITLE
Reg Select + Up Arrow

### ISSUE THREAD

**Issue by JakeSFR** [jun7/rox-filer#194] opened 2019-02-18 10:27 UTC
I'm not sure if this is intentional behaviour...
Just noticed that when I select some items using Reg Select and left-click "Up Arrow" icon, ROX doesn't go to the parent directory, but instead unselects everything, closes the Reg Select entry field and blinks the first, previously selected item:

![rox_reg_up](https://user-images.githubusercontent.com/6226504/52944415-a12d5580-336f-11e9-8b15-3307c3f2127d.gif)

**Comment by jun7** [comment] 2019-02-18 13:40
I think it is a bug. I will fix it.
Thank you.

**Comment by jun7** [comment] 2019-02-18 14:44
Ah it caused by #195. So I will close this when the commit fixing the #195 is uploaded.

**Comment by jun7** [comment] 2019-02-18 14:51
Thank you for reporting!

**Closed by jun7** 2019-02-18 14:51 UTC

**Comment by JakeSFR** [comment] 2019-02-18 16:06
Ok, I can't reproduce it anymore, thank you!

However, the other problem mentioned in https://github.com/jun7/rox-filer/issues/195 is still there.
Reg Select + clicking an **empty** area in toolbar changes dir to the first selected item.
If it's a file, ROX opens a non-existing dir (preceeded by ! sign).

Cheers!

**Comment by jun7** [comment] 2019-02-18 17:01
Is it fixed?

**Comment by jun7** [comment] 2019-02-18 17:07
I fixed the opening non-existing dirs.

>clicking an empty area in toolbar changes dir to the first selected item

is intentional behaviour. Yes it is not good but it is too complex.

**Comment by jun7** [comment] 2019-02-18 17:10
Ah but cheking reg select is not complex. So I will think of it.

**Comment by JakeSFR** [comment] 2019-02-18 17:34
> Is it fixed?

Yes, it is. Thanks again!

> > clicking an empty area in toolbar changes dir to the first selected item
> 
> is intentional behaviour.

Ok.
