### ISSUE TITLE
autoresize too narrow if toolbar without icons

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#204] opened 2020-01-30 10:30 UTC
Hello,
My toolbar is set to show text only, no icons, and the item count, and the window is set to auto-resize.  Rox displays the window too narrow, so some toolbar labels on the right side and the item count are cut off.  I think this is a bug, let me know your thinking. Thank you.

**Comment by jun7** [comment] 2020-02-01 07:32
Hi
Is
Options > Filer windows > Tools/Minibuffer > width of toolbar sets minimum width of window
ON ?

The calculation of width is not rightness. So something broken?

**Comment by step-** [comment] 2020-02-01 08:11
Yes, it is ON, see pictures.
Something is broken.
First open folder is OK: it shows SMALL icons and whole toolbar (CORRECT).

Move down to folder with few icons:
* icons automatically change from small size to REGULAR size
* window auto-resizes (smaller)
* toolbar cuts OFF some icons on the right size (BROKEN)

Move up to the previous folder
* icons automatically change from regular size to small size
* window auto-resizes (larger)
* toolbar shows all icons (CORRECT)

Thank you

![rox-20200201-001](https://user-images.githubusercontent.com/1414102/73589146-be9cf600-44d2-11ea-8b34-78cf811b07b8.png)
![rox-20200201-002](https://user-images.githubusercontent.com/1414102/73589147-be9cf600-44d2-11ea-992e-790deeb3ad1a.png)
![rox-20200201-003](https://user-images.githubusercontent.com/1414102/73589148-be9cf600-44d2-11ea-921d-8c4081e8bc3c.png)
![rox-20200201-004](https://user-images.githubusercontent.com/1414102/73589149-be9cf600-44d2-11ea-8fc1-a8386a14353b.png)

**Comment by jun7** [comment] 2020-02-01 10:11
I changed options to your pics but not reproduced.
Does It happen even with [text only] -> [icons only]?
Any other conditions?

**Comment by step-** [comment] 2020-02-01 11:43
> Does It happen even with [text only] -> [icons only]?
No.

> Any other conditions?
The attached file is all that I can think of.

[rox.tar.gz](https://github.com/jun7/rox-filer/files/4142485/rox.tar.gz)

**Comment by jun7** [comment] 2020-02-01 22:47
Hmm, not reproduced.
Does it happen without the .mo?

**Comment by step-** [comment] 2020-02-01 22:52
> Does it happen without the .mo?
Yes it does, I just tried.

**Comment by step-** [comment] 2020-02-02 07:01
I think I know why you can't reproduce: it depends on the theme. I've been using mine for so long that I forgot I had customized it for rox (#156).  You should be able to reproduce if you add the following lines to your gtk2 theme file (.gtkrc-mine or similar):
```
# http://rox.sourceforge.net/desktop/book/export/html/98.html
# https://github.com/jun7/rox-filer/issues/156
# Deleting everything between the braces resets to theme default values.
style "rox-toolbar-lbl" = "default"
{
fg[NORMAL]   = "#4e81c6"
fg[PRELIGHT] = "#4e81c6"
fg[ACTIVE]   = "#4e81c6"
}
style "rox-toolbar-btn-lbl" = "rox-toolbar-lbl"
{
font_name = "DejaVu Sans 16"
}
widget "rox-filer.*.GtkToolbar.GtkButton.*.GtkLabel" style "rox-toolbar-btn-lbl"
widget "rox-filer.*.GtkToolbar.GtkLabel" style "rox-toolbar-lbl"
```
If I comment out the last two lines and run rox -n the toolbar isn't cut off anymore.
I suppose the current code calculates toolbar width based on a smaller font-size: my system font size is 10pt, I only change it for the rox toolbar.

**Comment by jun7** [comment] 2020-02-02 07:53
Reproduced!
I will fix it.

**Comment by step-** [comment] 2020-02-02 07:53
Thank you!

**Comment by jun7** [comment] 2020-02-02 08:03
Thank you for reporting!

**Comment by jun7** [comment] 2020-02-02 08:20
Ah label is cut off.
Sorry I will fix it.

**Comment by step-** [comment] 2020-02-02 08:23
Yes I was just testing it and it's better but there are still cases when the toolbar is cut off.
When I change folder from small icon view (many items) going to large icon view (few items) the toolbar shrinks too much and cuts off some buttons.

**Comment by jun7** [comment] 2020-02-02 09:14
Not reproduced. Any other conditions?

**Comment by step-** [comment] 2020-02-02 09:17
With the .mo

**Comment by step-** [comment] 2020-02-02 09:18
Only with the .mo

**Comment by jun7** [comment] 2020-02-03 11:42
Hmm. The width of toolbar is calculated once when toolbar is created.
So If the bug is in the calculation, changing folder is not matter.
Does It happen only with changing folder from small to large?

**Comment by jun7** [comment] 2020-02-03 12:34
Ah I get it.
You have to add '┼' to N_("Size┼").
rox calculates width without '┼' and then added. The width of items are depend on max width. So it is serious.

**Comment by step-** [comment] 2020-02-03 12:38
Are you testing with the gtk2 styles that I mentioned previously?   If you do you will see the issue more clearly, because the font size is much bigger in those styles, so a calculation error is magnified.

**Comment by step-** [comment] 2020-02-03 12:43
> The width of items depend on max width.
Yes, I can see that when I hover the pointer over each button: they're all the same size large enough to  for 'Size┼'.

**Comment by step-** [comment] 2020-02-03 12:52
One more question, maybe a new issue.
With Options > Tools/Minibuffer > Toobar type: Icons only & Show totals of items ON,
sometimes the total of items isn't shown because the window shrinks too much. Changing folders can bring the item count back into view.  Has anything like this happened to you before?  Is it correct?

**Comment by jun7** [comment] 2020-02-03 21:43
Does it happen with HEAD(6bbef70700228fb3c81d6751fa40cc80a1d82017) ?

**Comment by step-** [comment] 2020-02-03 22:28
Thanks for the message. I hadn't thought about checking commits. I just built and tested 6bbef70. It's much better now but not quite fixed.   The last icon and the item counts are still cut off.

**AUTOMATIC**

![rox-20200203-003](https://user-images.githubusercontent.com/1414102/73696408-8537d680-46dc-11ea-9c80-5cd4af4568c6.png)


**AUTOMATIC**

![rox-20200203-004](https://user-images.githubusercontent.com/1414102/73696436-95e84c80-46dc-11ea-8e51-7ba9fbaa7a1e.png)

**MANUAL -- I resized to show whole toobar**

![rox-20200203-005](https://user-images.githubusercontent.com/1414102/73696465-a7315900-46dc-11ea-8698-743d340165bb.png)

**Comment by jun7** [comment] 2020-02-04 11:32
Changing a toolbar option(e.g. Show totals of items) re-calculate toolbar width. So could you check the result of changing it on a dir having few folders or empty?

**Comment by step-** [comment] 2020-02-04 11:48
Yes, good, changing a toolbar option recalculates width and all icons then come into view!

**Comment by jun7** [comment] 2020-02-04 11:58
So the calculation is now OK.
The width of the toolbar is narrow than the picts you post?
Then the size chars are suspect.
If not, Hmm I have no idea.

**Comment by step-** [comment] 2020-02-04 12:03
I'm not sure if you are asking something new.
The width of the toolbar can be like any of the three pictures I posted. It depends on what rox wants to show.  When rox resizes the toolbar too narrow the last icon and the item counts are out of view, cut off.

**Comment by step-** [comment] 2020-02-04 12:12
This with the .mo but without gtk styles always shows all buttons (but item count is still out of view)

![rox-20200204-002](https://user-images.githubusercontent.com/1414102/73743931-f664a180-474f-11ea-99f2-b2e8dbc1f538.png)

**Comment by jun7** [comment] 2020-02-04 12:23
You said that not fixed. So I want to know whether the calculation is OK or not.
Since the calculation is OK, there is another problems making windows narrow.
Isn't it fixed with reboot or changing dir?

**Comment by step-** [comment] 2020-02-04 12:25
Not fixed with reboot or changing dir.
Problem is fixed when no gtk style. See the last picture I posted.
Problem not fixed when gtk style.
Maybe depend on char size in gtk style property?

**Comment by jun7** [comment] 2020-02-04 12:33
Hmm the caluculation is not OK? Changing toolbar options with gtk style makes same result?

**Comment by jun7** [comment] 2020-02-04 12:36
Make sure that when changed gtk theme, reboot rox. the gtk_widget_size_request that used to get width of widgets not return proper size without reboot.

**Comment by step-** [comment] 2020-02-04 12:36
I don't know if the calculation is OK or not. I don't know what the calculation does.
Changing toolbar options with gtk style makes all buttons visible TEMPORARILY until I change the folder and then buttons are cut off again.

**Comment by step-** [comment] 2020-02-04 12:40
> Make sure that when changed gtk theme, reboot rox. the gtk_widget_size_request that used to get width of widgets not returns proper size without reboot.
Ah, sorry for not rebooting rox before.
Now I did. Then problem is not fixed when no gtk style.
With or without gtk style problem is the same: buttons out of view.

**Comment by jun7** [comment] 2020-02-04 12:46
Could you post a pict of theresult of changing options?

**Comment by step-** [comment] 2020-02-04 12:55
Sure.  With .mo and no gtk theme.

**BEFORE**

![rox-20200204-004](https://user-images.githubusercontent.com/1414102/73746546-b7d1e580-4755-11ea-9f1b-c350ab467246.png)

![rox-20200204-003](https://user-images.githubusercontent.com/1414102/73746573-c3251100-4755-11ea-868d-ec5462cad2d3.png)

**AFTER**

![rox-20200204-007](https://user-images.githubusercontent.com/1414102/73746581-cb7d4c00-4755-11ea-808f-e80562de330e.png)

![rox-20200204-006](https://user-images.githubusercontent.com/1414102/73746588-d33cf080-4755-11ea-840f-d8eaf9163d7e.png)

**Comment by jun7** [comment] 2020-02-04 13:14
You have to add '┼' to N_("Size┼") for the caluclation.

**Comment by step-** [comment] 2020-02-04 13:15
Which calculation? I didn't need to do any calculation.

**Comment by jun7** [comment] 2020-02-04 13:25
For the width of the toolbar.
You can see  buttons of the pict (rox-20200204-006) are narrow because it lacks '┼'.

**Comment by step-** [comment] 2020-02-04 13:44
Yes, I understand. But I don't understand what you want me to do.  I did not need to do any calculations.  Nothing I can do to calculate the width of the toolbar, sorry.
![rox-20200204-003-006](https://user-images.githubusercontent.com/1414102/73750064-d5ef1400-475c-11ea-9383-f64ba75637ec.png)

**Comment by step-** [comment] 2020-02-04 13:46
Maybe I understand.   You mean changing the .mo?
If you want to test a different .mo you can easily build one from the one I sent you.
Wait...

**Comment by step-** [comment] 2020-02-04 13:50
msgunfmt < ROX-Filer.mo > test.po
vim test.po
msgfmt -o test.mo test.po

**Comment by step-** [comment] 2020-02-04 13:56
Inside my .mo there are two lines:
```
msgid "Size"
msgstr "🌑"

msgid "Size┼"
msgstr "🌑"
```
The first one matches when your _N is "Size"
the second one matches when your _N is "Size┼"
The both return "🌑" because you append different characters after "Size".
If your code can define different _N("Size"+character) for all used characters then I can change the .po.

**Comment by jun7** [comment] 2020-02-04 17:36
I could not understand why both return "🌑".
So just change the bottom of "🌑" to "🌑┼".

**Comment by step-** [comment] 2020-02-04 17:55
Ah, right, you already changed the _N in 6bbef70 -- I hadn't seen that commit. Good.
...
Yes, I changed "🌑" to ""🌑┼" in .mo and now all buttons are visible!  Good!

Only last thing: sometimes item count is not visible.  I *think* it happens when the string ends with "(N hidden)".  In my Options > Filer windows > New window > show hidden files is OFF.

**Comment by jun7** [comment] 2020-02-05 11:31
It is normal.
Calculating the width of information label every time is not planned.

**Comment by step-** [comment] 2020-02-05 11:41
> Calculating the width of information label every time is not planned.
OK.

Does rox not calculate the information label when a new window opens?
Because when I start rox in $HOME from shell prompt, rox never shows info label, and $HOME has many hidden folders.

**Comment by jun7** [comment] 2020-02-05 12:20
Only when a new window opens makes no sense.
If you want more wider window you can change the base information string that I added by 6bbef70700228fb3c81d6751fa40cc80a1d82017 as you do tool labels.

**Comment by step-** [comment] 2020-02-05 12:26
> Only when a new window opens makes no sense.
Agreed.

> If you want more wider window
I don't.

I want the window to be wide enough to show the info label.
Currently the window is too narrow therefore it doesn't show the info label.
I have to resize the window manually to show the info label.
Is that normal?

**Comment by step-** [comment] 2020-02-07 07:13
Thank you very much for fixing #204 and all your patience and support!
I think you can close this issue (resolved).
To discuss about item count I have opened #207.

Thank you again

**Closed** 2020-02-07 07:40 UTC
Labels: enhancement
